---
title: "August 2025 Data Viz Challenge: Quartile Plus Visualization"
output: pdf_document
date: "2025-08-26"
---

## Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidytuesdayR)
```

# Pokemon

```{r read-pokemon-data}
# Read in Pokemon data

tuesdata <- tidytuesdayR::tt_load(2025, week = 13)
pokemon <- tuesdata$pokemon_df

head(pokemon)
```

```{r clean-data}
# Clean data

pokemon_clean <- pokemon %>%
  select(type_1, attack)
colnames(pokemon_clean)[colnames(pokemon_clean) == "type_1"] <- "type"

head(pokemon_clean)
```

```{r pokemon-boxplot}
ggplot(data = pokemon_clean, aes(x = type, y = attack, fill = type)) +
      geom_boxplot() +
  scale_fill_manual(values = c("#A6B91A", "#705746", "#6F35FC", "#F7D02C", "#D685AD", "#C22E28",
                     "#EE8130", "#A98FF3", "#735797", "#7AC74C", "#E2BF65", "#96D9D6",
                     "#A8A77A", "#A33EA1", "#F95587", "#B6A136", "#B7B7CE", "#6390F0")) +
  labs(x = "type", y = "attack points", title = "Attack Points by Pokemon Types") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5), axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.5), panel.grid = element_blank(),
        plot.background = element_rect(fill = 'white'), panel.background = element_rect(fill = 'white'),
        legend.position = 'none')
```
